### ISSUE TITLE
python version requirement

### ISSUE THREAD

**Issue by yang170** [sourav1547/cs598ftd#1]
I think python version requirement should be changed to 3.9 or higher in the readme and pdf file.
> We recommend using python version 3.6 or higher.

Type hint such as `tuple[Fp, bls12_381.G1]` is not supported until version 3.9. Run the code with python version < 3.9 will cause a type error.
![image](https://user-images.githubusercontent.com/26487716/155260174-c7b30cb5-607d-47dc-8d2f-941cf794590c.png)

**Comment by sourav1547** [comment]
Thanks! I have updated the code. Now it uses `'tuple[Fp, bls12_381.G1]'` as hint. Tested with python 3.8.10 and 3.9.10.
